### ISSUE TITLE
原数据源失效, 考虑新数据源

### ISSUE THREAD

**Issue by Doradx** [Doradx/ThreeGorgesWaterRegimenCollecter#8]
http://www.cjh.com.cn/index.html

**Comment by YanzhongSu** [comment]
Yeah, this URL cannot be opened anymore. https://www.ctg.com.cn/sxjt/sqqk/index.html

**Comment by Doradx** [comment]
new source: http://www.cjh.com.cn/sqindex.html

**Comment by Doradx** [comment]
new source: http://113.57.190.228:8001/web/Report/RiverReport

**Comment by YanzhongSu** [comment]
@Doradx Hi, is there anyway I can find the historical data for this new source? Thx.

**Comment by YanzhongSu** [comment]
> new source: http://113.57.190.228:8001/web/Report/RiverReport

@Doradx I just downloaded the excel file from your repo. Thank you for sharing it. I am trying to put together a scrape for this new site: http://113.57.190.228:8001/web/Report/RiverReport But struggling to get it to work. Have you by any chance got it working? Thank you in advance.

**Comment by Doradx** [comment]
new source: http://xxfb.mwr.cn/sq_dxsk.html
but it only shows the information today, and can't query the history data.

**Comment by Doradx** [comment]
> > new source: http://113.57.190.228:8001/web/Report/RiverReport
> 
> @Doradx I just downloaded the excel file from your repo. Thank you for sharing it. I am trying to put together a scrape for this new site: http://113.57.190.228:8001/web/Report/RiverReport But struggling to get it to work. Have you by any chance got it working? Thank you in advance.

I don't have space time to deal with it currently.
You need to know the structure of the POST query, which is a little difficult.

**Comment by Doradx** [comment]
> > > new source: http://113.57.190.228:8001/web/Report/RiverReport
> > 
> > 
> > @Doradx I just downloaded the excel file from your repo. Thank you for sharing it. I am trying to put together a scrape for this new site: http://113.57.190.228:8001/web/Report/RiverReport But struggling to get it to work. Have you by any chance got it working? Thank you in advance.
> 
> I don't have space time to deal with it currently.
> You need to know the structure of the POST query, which is a little difficult.

I have debug the [web site](http://113.57.190.228:8001/web/Report/RiverReport).
The valid query URL is:
`http://113.57.190.228:8001/Web/Report/GetRiverData?date={date_you_want_to_search}`
example:
`http://113.57.190.228:8001/Web/Report/GetRiverData?date=2021-05-12%2008:00`

Just do it.
